export function browserPage(nonce: string): string {
  return String.raw`<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="referrer" content="no-referrer">
<title>Pi Reader</title>
<style nonce="${nonce}">
:root{color-scheme:light dark;--bg:#f7f5ef;--panel:#fff;--text:#24231f;--muted:#706d64;--line:#d9d4c8;--accent:#7357c7;--selected:#fff1a8;--danger:#b33a3a} @media(prefers-color-scheme:dark){:root{--bg:#171713;--panel:#22221d;--text:#e9e6dc;--muted:#aaa69b;--line:#3d3c34;--accent:#b5a0ff;--selected:#5b501e;--danger:#ff8c8c}}
*{box-sizing:border-box} body{margin:0;background:var(--bg);color:var(--text);font:16px/1.6 ui-sans-serif,system-ui,-apple-system,sans-serif} button,input,select,textarea{font:inherit;color:inherit} button{border:1px solid var(--line);background:var(--panel);border-radius:.45rem;padding:.42rem .7rem;cursor:pointer} button:hover{border-color:var(--accent)} button:disabled{opacity:.55;cursor:not-allowed}.primary{background:var(--accent);color:white;border-color:var(--accent)}
header{position:sticky;top:0;z-index:4;background:color-mix(in srgb,var(--bg) 94%,transparent);backdrop-filter:blur(8px);border-bottom:1px solid var(--line);padding:.7rem 1rem}.brand{display:flex;gap:.7rem;align-items:baseline;margin-bottom:.55rem}.brand strong{color:var(--accent);letter-spacing:.06em}.model{color:var(--muted);font-size:.85rem}.urlbar{display:flex;gap:.5rem}.urlbar input{flex:1;min-width:0;background:var(--panel);border:1px solid var(--line);border-radius:.45rem;padding:.5rem .65rem}
main{display:grid;grid-template-columns:minmax(0,1fr) minmax(20rem,34rem);height:calc(100vh - 106px)}.reading,.side{overflow:auto}.reading{padding:2.2rem clamp(1.2rem,5vw,5rem);border-right:1px solid var(--line)}article{max-width:48rem;margin:auto;font-family:ui-serif,Georgia,serif;font-size:1.08rem}article h1{font-size:2.15rem;line-height:1.15}article h2{margin-top:2.2rem}article pre,.message pre{overflow:auto;background:var(--bg);padding:1rem;border-radius:.4rem}article code,.message code{font-family:ui-monospace,monospace}article a,.message a{color:var(--accent)} blockquote{border-left:3px solid var(--accent);margin-left:0;padding-left:1rem;color:var(--muted)}
.side{display:flex;flex-direction:column;background:var(--panel)}.sidehead{padding:.8rem 1rem;border-bottom:1px solid var(--line);display:flex;gap:.5rem;align-items:center}.sidehead select{min-width:0;flex:1;background:var(--bg);border:1px solid var(--line);padding:.4rem}.messages{padding:1rem;flex:1;overflow:auto}.message{padding-bottom:1rem;margin-bottom:1rem;border-bottom:1px solid var(--line)}.message h3{font-size:1rem;margin:.2rem 0}.quote{white-space:pre-wrap;border-left:3px solid var(--accent);padding:.45rem .7rem;background:var(--bg);font-size:.9rem;color:var(--muted);max-height:10rem;overflow:auto}.selection{padding:.7rem 1rem;border-top:1px solid var(--line);background:var(--bg)}.selection p{white-space:pre-wrap;max-height:7rem;overflow:auto;margin:.4rem 0}.actions{display:flex;gap:.4rem;flex-wrap:wrap}.ask{padding:.7rem 1rem;border-top:1px solid var(--line)}textarea{width:100%;resize:vertical;min-height:4.5rem;background:var(--bg);border:1px solid var(--line);border-radius:.45rem;padding:.55rem}.askrow{display:flex;justify-content:space-between;gap:.5rem;margin-top:.45rem}.status{font-size:.88rem;color:var(--muted);padding:.45rem 1rem;border-top:1px solid var(--line)}.status.error{color:var(--danger)}.empty{color:var(--muted);text-align:center;margin-top:18vh}.busy{animation:pulse 1.2s infinite alternate}@keyframes pulse{to{opacity:.55}}
@media(max-width:850px){main{display:block;height:auto}.reading{border:0;min-height:70vh}.side{min-height:80vh;border-top:1px solid var(--line)}}
</style>
</head>
<body>
<header><div class="brand"><strong>π READER</strong><span class="model" id="model"></span><span class="model">in memory only</span></div><form class="urlbar" id="loadForm"><input id="url" type="url" inputmode="url" placeholder="https://example.com/article" aria-label="Article URL"><button class="primary">Load</button></form></header>
<main><section class="reading"><article id="article"><p class="empty">Load an article to begin.</p></article></section><aside class="side"><div class="sidehead"><select id="pages" aria-label="Loaded pages"><option>No loaded pages</option></select><button id="articleMode">Article</button><button id="summaryMode">Recap</button></div><div class="messages" id="messages"><p class="empty">Questions and answers stay scoped to this URL.</p></div><section class="selection" id="selection" hidden><strong>Selected passage</strong><p id="selectedText"></p><div class="actions"><button class="primary" id="explain">Explain</button><button id="focusAsk">Ask</button><button id="clearSelection">Clear</button></div></section><form class="ask" id="askForm"><textarea id="question" placeholder="Ask about this article…"></textarea><div class="askrow"><button type="button" id="summarize">Summarize my learnings</button><span><button type="button" id="cancel" hidden>Cancel</button> <button class="primary" id="askButton">Ask</button></span></div></form><div class="status" id="status">Connecting to pi…</div></aside></main>
<script nonce="${nonce}">
'use strict';
const base=location.pathname.endsWith('/')?location.pathname:location.pathname+'/';
const $=id=>document.getElementById(id); let state; let selected=''; let mode='article'; let requestId=0;
const safeUrl=value=>{try{const u=new URL(value);return u.protocol==='http:'||u.protocol==='https:'?u.href:null}catch{return null}};
function inline(parent,text){const re=/\[([^\]]+)\]\((https?:\/\/[^)\s]+)\)|\x60([^\x60]+)\x60|\*\*([^*]+)\*\*|\*([^*]+)\*/g;let at=0,m;while((m=re.exec(text))){parent.append(document.createTextNode(text.slice(at,m.index)));let node;if(m[1]){node=document.createElement('a');node.textContent=m[1];node.href=safeUrl(m[2])||'#';node.target='_blank';node.rel='noopener noreferrer'}else if(m[3]){node=document.createElement('code');node.textContent=m[3]}else{node=document.createElement(m[4]?'strong':'em');node.textContent=m[4]||m[5]}parent.append(node);at=re.lastIndex}parent.append(document.createTextNode(text.slice(at)))}
function markdown(text,root){root.replaceChildren();const lines=(text||'').split('\n');let i=0;while(i<lines.length){const line=lines[i];if(!line.trim()){i++;continue}if(/^\x60\x60\x60/.test(line)){const code=[];i++;while(i<lines.length&&!/^\x60\x60\x60/.test(lines[i]))code.push(lines[i++]);i++;const pre=document.createElement('pre'),c=document.createElement('code');c.textContent=code.join('\n');pre.append(c);root.append(pre);continue}const heading=line.match(/^(#{1,6})\s+(.+)/);if(heading){const h=document.createElement('h'+heading[1].length);inline(h,heading[2]);root.append(h);i++;continue}if(/^([-*_])(?:\s*\1){2,}\s*$/.test(line)){root.append(document.createElement('hr'));i++;continue}if(/^>\s?/.test(line)){const q=document.createElement('blockquote'),parts=[];while(i<lines.length&&/^>\s?/.test(lines[i]))parts.push(lines[i++].replace(/^>\s?/,''));inline(q,parts.join('\n'));root.append(q);continue}const list=line.match(/^\s*(?:([-+*])|(\d+)\.)\s+(.+)/);if(list){const tag=list[2]?'ol':'ul',el=document.createElement(tag);while(i<lines.length){const item=lines[i].match(/^\s*(?:([-+*])|(\d+)\.)\s+(.+)/);if(!item||Boolean(item[2])!==Boolean(list[2]))break;const li=document.createElement('li');inline(li,item[3]);el.append(li);i++}root.append(el);continue}const parts=[line];i++;while(i<lines.length&&lines[i].trim()&&!/^(#{1,6})\s|^\x60\x60\x60|^>\s?|^\s*(?:[-+*]|\d+\.)\s+/.test(lines[i]))parts.push(lines[i++]);const p=document.createElement('p');inline(p,parts.join(' '));root.append(p)}}
async function api(action='',payload,method=payload?'POST':'GET'){const options={method,headers:{'Accept':'application/json'}};if(payload!==undefined){options.headers['Content-Type']='application/json';options.body=JSON.stringify(payload)}const response=await fetch(base+'api/'+action,options);const data=await response.json().catch(()=>({error:'Invalid response from pi.'}));if(!response.ok)throw new Error(data.error||('Request failed: '+response.status));return data}
function render(){if(!state)return;$('model').textContent=state.model+' ·';$('status').textContent=state.status;$('status').className='status'+(state.error?' error':'')+(state.busy?' busy':'');$('cancel').hidden=!state.busy;for(const el of document.querySelectorAll('button,input,textarea,select'))if(el.id!=='cancel')el.disabled=state.busy;const current=state.current;if(current&&document.activeElement!==$('url'))$('url').value=current.article.url;const pages=$('pages');pages.replaceChildren();if(state.pages.length){for(const page of state.pages){const option=document.createElement('option');option.value=page.url;option.textContent=page.title;option.selected=current&&page.url===current.article.url;pages.append(option)}}else{const option=document.createElement('option');option.textContent='No loaded pages';pages.append(option)}const article=$('article');if(current){markdown(mode==='summary'?(current.summary||'*No recap yet. Choose Summarize my learnings.*'):current.article.markdown,article)}else{article.replaceChildren();const empty=document.createElement('p');empty.className='empty';empty.textContent='Load an article to begin.';article.append(empty)}const messages=$('messages');messages.replaceChildren();if(current&&current.exchanges.length){current.exchanges.forEach((exchange,index)=>{const box=document.createElement('section');box.className='message';const h=document.createElement('h3');h.textContent='Q'+(index+1)+': '+exchange.question;box.append(h);if(exchange.selection){const q=document.createElement('div');q.className='quote';q.textContent=exchange.selection;box.append(q)}const answer=document.createElement('div');markdown(exchange.answer,answer);box.append(answer);messages.append(box)})}else{const p=document.createElement('p');p.className='empty';p.textContent='Ask a question about this article.';messages.append(p)}if(current&&current.selection&&!selected)selected=current.selection;showSelection();$('articleMode').disabled=mode==='article'||state.busy;$('summaryMode').disabled=mode==='summary'||state.busy||!current?.summary}
function showSelection(){const box=$('selection');box.hidden=!selected;$('selectedText').textContent=selected}
async function refresh(){state=await api('state');render()}
async function run(action,payload){const id=++requestId;try{state={...state,busy:true,status:action==='summary'?'Summarizing…':action==='load'?'Loading article…':'Asking pi…'};render();const result=await api(action,payload);if(id===requestId){state=result;selected=state.current?.selection||'';render();$('messages').scrollTop=$('messages').scrollHeight}return !result.error}catch(error){if(id===requestId){state={...state,busy:false,error:true,status:error.message};render()}return false}}
$('loadForm').addEventListener('submit',event=>{event.preventDefault();selected='';mode='article';run('load',{url:$('url').value})});
$('askForm').addEventListener('submit',async event=>{event.preventDefault();const question=$('question').value.trim();if(question&&await run('ask',{question,selection:selected}))$('question').value=''});
$('explain').onclick=()=>run('explain',{selection:selected});$('focusAsk').onclick=()=>{$('question').focus()};$('clearSelection').onclick=async()=>{selected='';showSelection();state=await api('select',{selection:''});render()};$('summarize').onclick=()=>{mode='summary';run('summary',{})};$('cancel').onclick=async()=>{requestId++;state=await api('cancel',{});render()};$('articleMode').onclick=()=>{mode='article';render()};$('summaryMode').onclick=()=>{mode='summary';render()};$('pages').onchange=()=>{selected='';mode='article';run('load',{url:$('pages').value})};
function captureSelection(){const selection=getSelection();if(!selection||selection.isCollapsed)return;const range=selection.getRangeAt(0);const node=range.commonAncestorContainer.nodeType===1?range.commonAncestorContainer:range.commonAncestorContainer.parentElement;if(!$('article').contains(node))return;selected=selection.toString().replace(/\s+/g,' ').trim().slice(0,20000);showSelection();api('select',{selection:selected}).catch(error=>{$('status').textContent=error.message;$('status').className='status error'})}
$('article').addEventListener('mouseup',captureSelection);$('article').addEventListener('keyup',captureSelection);$('question').addEventListener('keydown',event=>{if((event.metaKey||event.ctrlKey)&&event.key==='Enter')$('askForm').requestSubmit()});
refresh().catch(error=>{$('status').textContent=error.message;$('status').className='status error'});
</script>
</body></html>`;
}
